version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - apocalipssi-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - apocalipssi-net
    depends_on:
      - backend

networks:
  apocalipssi-net:
